# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/RE58C2/setup-makefiles.sh

$(warning Including RE58C2-vendor.mk)


PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/etc/audio_effects.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/audio_effects.conf \
    vendor/realme/RE58C2/proprietary/etc/libnfc-nci.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/libnfc-nci.conf \
    vendor/realme/RE58C2/proprietary/etc/seccomp_policy/mediacodec.policy:$(TARGET_COPY_OUT_SYSTEM)/etc/seccomp_policy/mediacodec.policy \
    vendor/realme/RE58C2/proprietary/etc/temperature_profile/sys_high_temperature.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/temperature_profile/sys_high_temperature.xml \
    vendor/realme/RE58C2/proprietary/lib/libois_algorithm_jni.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libois_algorithm_jni.so \
    vendor/realme/RE58C2/proprietary/lib/libremotedisplay.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libremotedisplay.so \
    vendor/realme/RE58C2/proprietary/lib/libstagefright_bufferpool@2.0.1.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstagefright_bufferpool@2.0.1.so \
    vendor/realme/RE58C2/proprietary/lib/libstagefright_codecbase.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstagefright_codecbase.so \
    vendor/realme/RE58C2/proprietary/lib/libstagefright_framecapture_utils.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstagefright_framecapture_utils.so \
    vendor/realme/RE58C2/proprietary/lib/libstagefright_surface.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstagefright_surface.so \
    vendor/realme/RE58C2/proprietary/lib/libstagefright_surface_utils.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstagefright_surface_utils.so \
    vendor/realme/RE58C2/proprietary/lib/libstagefright_wfd.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libstagefright_wfd.so \
    vendor/realme/RE58C2/proprietary/lib64/libois_algorithm_jni.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libois_algorithm_jni.so \
    vendor/realme/RE58C2/proprietary/lib64/libremotedisplay.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libremotedisplay.so \
    vendor/realme/RE58C2/proprietary/lib64/libstagefright_bufferpool@2.0.1.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libstagefright_bufferpool@2.0.1.so \
    vendor/realme/RE58C2/proprietary/lib64/libstagefright_codecbase.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libstagefright_codecbase.so \
    vendor/realme/RE58C2/proprietary/lib64/libstagefright_framecapture_utils.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libstagefright_framecapture_utils.so \
    vendor/realme/RE58C2/proprietary/lib64/libstagefright_surface.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libstagefright_surface.so \
    vendor/realme/RE58C2/proprietary/lib64/libstagefright_surface_utils.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libstagefright_surface_utils.so \
    vendor/realme/RE58C2/proprietary/lib64/libstagefright_wfd.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libstagefright_wfd.so \
    vendor/realme/RE58C2/proprietary/odm/etc/audio/audio_policy_configuration.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_policy_configuration.xml \
    vendor/realme/RE58C2/proprietary/odm/etc/audio/audio_policy_configuration_a2dp_offload_disabled.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_policy_configuration_a2dp_offload_disabled.xml \
    vendor/realme/RE58C2/proprietary/odm/etc/audio/audio_policy_volumes.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_policy_volumes.xml \
    vendor/realme/RE58C2/proprietary/odm/etc/audio/bluetooth_audio_policy_configuration.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/bluetooth_audio_policy_configuration.xml \
    vendor/realme/RE58C2/proprietary/odm/etc/audio/bluetooth_audio_policy_configuration_disable_offload.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/bluetooth_audio_policy_configuration_disable_offload.xml \
    vendor/realme/RE58C2/proprietary/odm/etc/audio/default_volume_tables.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/default_volume_tables.xml \
    vendor/realme/RE58C2/proprietary/odm/etc/audio/primary_audio_policy_configuration.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/primary_audio_policy_configuration.xml \
    vendor/realme/RE58C2/proprietary/odm/etc/audio/r_submix_audio_policy_configuration.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/r_submix_audio_policy_configuration.xml \
    vendor/realme/RE58C2/proprietary/odm/etc/audio/usb_audio_policy_configuration.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/usb_audio_policy_configuration.xml \
    vendor/realme/RE58C2/proprietary/odm/etc/audio_params/sprd/audio_pga.xml:$(TARGET_COPY_OUT_ODM)/etc/audio_params/sprd/audio_pga.xml \
    vendor/realme/RE58C2/proprietary/odm/etc/audio_params/sprd/audio_process.xml:$(TARGET_COPY_OUT_ODM)/etc/audio_params/sprd/audio_process.xml \
    vendor/realme/RE58C2/proprietary/odm/etc/audio_params/sprd/audio_structure.xml:$(TARGET_COPY_OUT_ODM)/etc/audio_params/sprd/audio_structure.xml \
    vendor/realme/RE58C2/proprietary/odm/etc/audio_params/sprd/audioparam_config.xml:$(TARGET_COPY_OUT_ODM)/etc/audio_params/sprd/audioparam_config.xml \
    vendor/realme/RE58C2/proprietary/odm/etc/audio_params/sprd/codec.xml:$(TARGET_COPY_OUT_ODM)/etc/audio_params/sprd/codec.xml \
    vendor/realme/RE58C2/proprietary/odm/etc/audio_params/sprd/cvs.xml:$(TARGET_COPY_OUT_ODM)/etc/audio_params/sprd/cvs.xml \
    vendor/realme/RE58C2/proprietary/odm/etc/audio_params/sprd/dsp_vbc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio_params/sprd/dsp_vbc.xml \
    vendor/realme/RE58C2/proprietary/odm/etc/audio_params/sprd/version1/audio_pga.xml:$(TARGET_COPY_OUT_ODM)/etc/audio_params/sprd/version1/audio_pga.xml \
    vendor/realme/RE58C2/proprietary/odm/etc/audio_params/sprd/version1/audio_process.xml:$(TARGET_COPY_OUT_ODM)/etc/audio_params/sprd/version1/audio_process.xml \
    vendor/realme/RE58C2/proprietary/odm/etc/audio_params/sprd/version1/audio_structure.xml:$(TARGET_COPY_OUT_ODM)/etc/audio_params/sprd/version1/audio_structure.xml \
    vendor/realme/RE58C2/proprietary/odm/etc/audio_params/sprd/version1/audioparam_config.xml:$(TARGET_COPY_OUT_ODM)/etc/audio_params/sprd/version1/audioparam_config.xml \
    vendor/realme/RE58C2/proprietary/odm/etc/audio_params/sprd/version1/codec.xml:$(TARGET_COPY_OUT_ODM)/etc/audio_params/sprd/version1/codec.xml \
    vendor/realme/RE58C2/proprietary/odm/etc/audio_params/sprd/version1/cvs.xml:$(TARGET_COPY_OUT_ODM)/etc/audio_params/sprd/version1/cvs.xml \
    vendor/realme/RE58C2/proprietary/odm/etc/audio_params/sprd/version1/dsp_vbc.xml:$(TARGET_COPY_OUT_ODM)/etc/audio_params/sprd/version1/dsp_vbc.xml \
    vendor/realme/RE58C2/proprietary/odm/etc/audio_pcm.xml:$(TARGET_COPY_OUT_ODM)/etc/audio_pcm.xml \
    vendor/realme/RE58C2/proprietary/odm/etc/audio_route.xml:$(TARGET_COPY_OUT_ODM)/etc/audio_route.xml \
    vendor/realme/RE58C2/proprietary/odm/etc/build_EEA_3760.prop:$(TARGET_COPY_OUT_ODM)/etc/build_EEA_3760.prop \
    vendor/realme/RE58C2/proprietary/odm/etc/build_EEA_3761.prop:$(TARGET_COPY_OUT_ODM)/etc/build_EEA_3761.prop \
    vendor/realme/RE58C2/proprietary/odm/etc/build_EEA_3765.prop:$(TARGET_COPY_OUT_ODM)/etc/build_EEA_3765.prop \
    vendor/realme/RE58C2/proprietary/odm/etc/build_EEA_3830.prop:$(TARGET_COPY_OUT_ODM)/etc/build_EEA_3830.prop \
    vendor/realme/RE58C2/proprietary/odm/etc/build_EEA_3834.prop:$(TARGET_COPY_OUT_ODM)/etc/build_EEA_3834.prop \
    vendor/realme/RE58C2/proprietary/odm/etc/build_IN_3834.prop:$(TARGET_COPY_OUT_ODM)/etc/build_IN_3834.prop \
    vendor/realme/RE58C2/proprietary/odm/etc/build_RU_3760.prop:$(TARGET_COPY_OUT_ODM)/etc/build_RU_3760.prop \
    vendor/realme/RE58C2/proprietary/odm/etc/build_RU_3761.prop:$(TARGET_COPY_OUT_ODM)/etc/build_RU_3761.prop \
    vendor/realme/RE58C2/proprietary/odm/etc/build_RU_3762.prop:$(TARGET_COPY_OUT_ODM)/etc/build_RU_3762.prop \
    vendor/realme/RE58C2/proprietary/odm/etc/build_RU_3763.prop:$(TARGET_COPY_OUT_ODM)/etc/build_RU_3763.prop \
    vendor/realme/RE58C2/proprietary/odm/etc/build_RU_3765.prop:$(TARGET_COPY_OUT_ODM)/etc/build_RU_3765.prop \
    vendor/realme/RE58C2/proprietary/odm/etc/build_RU_3830.prop:$(TARGET_COPY_OUT_ODM)/etc/build_RU_3830.prop \
    vendor/realme/RE58C2/proprietary/odm/etc/build_RU_3831.prop:$(TARGET_COPY_OUT_ODM)/etc/build_RU_3831.prop \
    vendor/realme/RE58C2/proprietary/odm/etc/build_RU_3834.prop:$(TARGET_COPY_OUT_ODM)/etc/build_RU_3834.prop \
    vendor/realme/RE58C2/proprietary/odm/etc/build_T2_3760.prop:$(TARGET_COPY_OUT_ODM)/etc/build_T2_3760.prop \
    vendor/realme/RE58C2/proprietary/odm/etc/build_T2_3761.prop:$(TARGET_COPY_OUT_ODM)/etc/build_T2_3761.prop \
    vendor/realme/RE58C2/proprietary/odm/etc/build_T2_3762.prop:$(TARGET_COPY_OUT_ODM)/etc/build_T2_3762.prop \
    vendor/realme/RE58C2/proprietary/odm/etc/build_T2_3763.prop:$(TARGET_COPY_OUT_ODM)/etc/build_T2_3763.prop \
    vendor/realme/RE58C2/proprietary/odm/etc/build_T2_3765.prop:$(TARGET_COPY_OUT_ODM)/etc/build_T2_3765.prop \
    vendor/realme/RE58C2/proprietary/odm/etc/build_T2_3830.prop:$(TARGET_COPY_OUT_ODM)/etc/build_T2_3830.prop \
    vendor/realme/RE58C2/proprietary/odm/etc/build_T2_3831.prop:$(TARGET_COPY_OUT_ODM)/etc/build_T2_3831.prop \
    vendor/realme/RE58C2/proprietary/odm/etc/build_T2_3834.prop:$(TARGET_COPY_OUT_ODM)/etc/build_T2_3834.prop \
    vendor/realme/RE58C2/proprietary/odm/etc/build_TELCEL_3760.prop:$(TARGET_COPY_OUT_ODM)/etc/build_TELCEL_3760.prop \
    vendor/realme/RE58C2/proprietary/odm/etc/build_TELCEL_3765.prop:$(TARGET_COPY_OUT_ODM)/etc/build_TELCEL_3765.prop \
    vendor/realme/RE58C2/proprietary/odm/etc/build_TELCEL_3834.prop:$(TARGET_COPY_OUT_ODM)/etc/build_TELCEL_3834.prop \
    vendor/realme/RE58C2/proprietary/odm/etc/build_TR_3760.prop:$(TARGET_COPY_OUT_ODM)/etc/build_TR_3760.prop \
    vendor/realme/RE58C2/proprietary/odm/etc/build_TR_3765.prop:$(TARGET_COPY_OUT_ODM)/etc/build_TR_3765.prop \
    vendor/realme/RE58C2/proprietary/odm/etc/build_TR_3830.prop:$(TARGET_COPY_OUT_ODM)/etc/build_TR_3830.prop \
    vendor/realme/RE58C2/proprietary/odm/etc/build_TR_3834.prop:$(TARGET_COPY_OUT_ODM)/etc/build_TR_3834.prop \
    vendor/realme/RE58C2/proprietary/odm/etc/build_VN_3834.prop:$(TARGET_COPY_OUT_ODM)/etc/build_VN_3834.prop \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/configs/ov13b10_ly:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/configs/ov13b10_ly \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/configs/ov50d40_mipi_raw:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/configs/ov50d40_mipi_raw \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/configs/ov8856_front_ly:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/configs/ov8856_front_ly \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/configs/ov8856_front_seasons:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/configs/ov8856_front_seasons \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/configs/s5k5e9yu05:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/configs/s5k5e9yu05 \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/configs/s5khm6sx03_qt:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/configs/s5khm6sx03_qt \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/configs/s5kjn1_mipi_raw:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/configs/s5kjn1_mipi_raw \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/B1VLf4peM:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/B1VLf4peM \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/B1aMqioxf:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/B1aMqioxf \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/B1nmcmWbG:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/B1nmcmWbG \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/B1si_XbZz:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/B1si_XbZz \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/B612Pretty.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/B612Pretty.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/BJJAwoigM:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/BJJAwoigM \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/BJyKIwqxz:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/BJyKIwqxz \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/BeautyplusMellow-5.CUBE.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/BeautyplusMellow-5.CUBE.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/ByW7g4bbf:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/ByW7g4bbf \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/ByYo3If:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/ByYo3If \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/BycYf7WWz:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/BycYf7WWz \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/DL_A_Pacman.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/DL_A_Pacman.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/DL_D_G4.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/DL_D_G4.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/DL_L_B6.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/DL_L_B6.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/Emerald.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/Emerald.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/EyxRbD2UCe:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/EyxRbD2UCe \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/FaceappGrayscale.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/FaceappGrayscale.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/InsClarendon.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/InsClarendon.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/InsJuno.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/InsJuno.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/InsValencia-2.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/InsValencia-2.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/Martin.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/Martin.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/OPLUSR0604.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/OPLUSR0604.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/PP1-soft-2.6.CUBE.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/PP1-soft-2.6.CUBE.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/PP2-pop-4.1.CUBE.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/PP2-pop-4.1.CUBE.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/PP3-mono-3.3.CUBE.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/PP3-mono-3.3.CUBE.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/Radiance.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/Radiance.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/SJ3mbr6ef:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/SJ3mbr6ef \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/Serenity.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/Serenity.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/SkpZ8ebbz:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/SkpZ8ebbz \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/SnapseedBright.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/SnapseedBright.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/SweetSnapAlice-3.CUBE.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/SweetSnapAlice-3.CUBE.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/Sy4uLSTgf:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/Sy4uLSTgf \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/Syt2KeZZf:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/Syt2KeZZf \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/V01-landscape-2.6.CUBE.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/V01-landscape-2.6.CUBE.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/V02-portrait-2.5.CUBE.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/V02-portrait-2.5.CUBE.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/V03-food-2.0.CUBE.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/V03-food-2.0.CUBE.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/V04-night-1.3.CUBE.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/V04-night-1.3.CUBE.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/V05-mono-3.3.CUBE.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/V05-mono-3.3.CUBE.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/YoucamAdorable80.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/YoucamAdorable80.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/b-w-P8.CUBE.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/b-w-P8.CUBE.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/black_gold.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/black_gold.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/blackandwhite.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/blackandwhite.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/bowu-2.1.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/bowu-2.1.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/bright_coloured.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/bright_coloured.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/calm-V5.CUBE.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/calm-V5.CUBE.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/candy-P7.CUBE.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/candy-P7.CUBE.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/cola.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/cola.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/cyberpunk-kitsch-3.1.CUBE.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/cyberpunk-kitsch-3.1.CUBE.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/cyberpunk-neoMilitarism-2.4-final.CUBE.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/cyberpunk-neoMilitarism-2.4-final.CUBE.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/default:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/default \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/delight-P3.CUBE.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/delight-P3.CUBE.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/delight-V1.CUBE.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/delight-V1.CUBE.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/drjw1994.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/drjw1994.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/drjw2010.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/drjw2010.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/f_bin_hideaki:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/f_bin_hideaki \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/f_candy_water_weak.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/f_candy_water_weak.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/f_contrast_gray_face_dark:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/f_contrast_gray_face_dark \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/f_fuji_strong.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/f_fuji_strong.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/f_japan_strong.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/f_japan_strong.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/farewell-V7.CUBE.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/farewell-V7.CUBE.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/fuji-eterna-v2.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/fuji-eterna-v2.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/fuji.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/fuji.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/gourmet.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/gourmet.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/gt-24hour-city.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/gt-24hour-city.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/gt-3dcity.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/gt-3dcity.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/gt-after-glow.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/gt-after-glow.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/gt-azure-water.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/gt-azure-water.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/gt-beach.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/gt-beach.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/gt-blue-water.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/gt-blue-water.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/gt-coco-grove.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/gt-coco-grove.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/gt-crisp-fall.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/gt-crisp-fall.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/gt-desert.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/gt-desert.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/gt-earth.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/gt-earth.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/gt-glazed-tile.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/gt-glazed-tile.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/gt-japan.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/gt-japan.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/gt-lake.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/gt-lake.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/gt-mountainous.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/gt-mountainous.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/gt-old-times.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/gt-old-times.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/gt-quietly-ele.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/gt-quietly-ele.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/gt-rosy.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/gt-rosy.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/gt-steaming.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/gt-steaming.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/interstellar_space.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/interstellar_space.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/jiari-2.0.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/jiari-2.0.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/jw_sun.CUBE.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/jw_sun.CUBE.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/jw_surprise.CUBE.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/jw_surprise.CUBE.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/kodak.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/kodak.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/lvtu-2.0.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/lvtu-2.0.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/meiwei-2.2.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/meiwei-2.2.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/mellow-V3.CUBE.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/mellow-V3.CUBE.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/misty-P5.CUBE.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/misty-P5.CUBE.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/misty-V4.CUBE.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/misty-V4.CUBE.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/mono.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/mono.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/morandi.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/morandi.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/natural-P1.CUBE.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/natural-P1.CUBE.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/natural.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/natural.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/neon-2020.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/neon-2020.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/oplus-black-gold.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/oplus-black-gold.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/oplus-cyberpunk.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/oplus-cyberpunk.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/oplus-nightcity.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/oplus-nightcity.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/oplus-r-black-gold-1.1-RGB.CUBE.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/oplus-r-black-gold-1.1-RGB.CUBE.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/oplus-r-cyberpunk-RGB.CUBE.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/oplus-r-cyberpunk-RGB.CUBE.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/oplus-r-infra-RGB.CUBE.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/oplus-r-infra-RGB.CUBE.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/oplus-yellow-blue.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/oplus-yellow-blue.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/oplus_SAREK_III.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/oplus_SAREK_III.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/oplus_VAEROY_III.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/oplus_VAEROY_III.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/oplus_YLLAAS.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/oplus_YLLAAS.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/oplus_r4.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/oplus_r4.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/oplus_r5.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/oplus_r5.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/oplus_r6.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/oplus_r6.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/oplus_video_filter_black_and_white:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/oplus_video_filter_black_and_white \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/oplus_video_filter_highlight:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/oplus_video_filter_highlight \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/oplus_video_filter_ins:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/oplus_video_filter_ins \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/oplus_video_filter_natal:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/oplus_video_filter_natal \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/oplus_video_filter_olympus:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/oplus_video_filter_olympus \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/oplus_video_filter_plain:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/oplus_video_filter_plain \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/oplus_video_filter_show:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/oplus_video_filter_show \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/oplus_video_filter_solar:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/oplus_video_filter_solar \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/oplus_video_filter_strong:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/oplus_video_filter_strong \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/oplus_video_filter_west:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/oplus_video_filter_west \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/oppo_video_filter_black_and_white:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/oppo_video_filter_black_and_white \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/oppo_video_filter_highlight:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/oppo_video_filter_highlight \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/oppo_video_filter_ins:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/oppo_video_filter_ins \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/oppo_video_filter_natal:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/oppo_video_filter_natal \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/oppo_video_filter_olympus:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/oppo_video_filter_olympus \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/oppo_video_filter_plain:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/oppo_video_filter_plain \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/oppo_video_filter_show:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/oppo_video_filter_show \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/oppo_video_filter_solar:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/oppo_video_filter_solar \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/oppo_video_filter_strong:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/oppo_video_filter_strong \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/oppo_video_filter_west:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/oppo_video_filter_west \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/p4_1.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/p4_1.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/p4_2.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/p4_2.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/p4_3.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/p4_3.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/p4_4.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/p4_4.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/qiuri-2.0.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/qiuri-2.0.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/r1JaFSZZG:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/r1JaFSZZG \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/r1PrfoolG:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/r1PrfoolG \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/rJ5g5vPWG:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/rJ5g5vPWG \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/rJxJtmaez:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/rJxJtmaez \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/red-red.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/red-red.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/rkMhq4ZWf:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/rkMhq4ZWf \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/rkx5u4Zbf:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/rkx5u4Zbf \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/senlin-2.0.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/senlin-2.0.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/serene-P9.CUBE.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/serene-P9.CUBE.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/sky-blue.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/sky-blue.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/sweet-P2.CUBE.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/sweet-P2.CUBE.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/sweet-V2.CUBE.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/sweet-V2.CUBE.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/tree-green.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/tree-green.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/type_fuji_acros:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/type_fuji_acros \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/type_fuji_astia:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/type_fuji_astia \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/type_fuji_chrome:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/type_fuji_chrome \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/type_fuji_provia:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/type_fuji_provia \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/type_fuji_velvia:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/type_fuji_velvia \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/vivid-cool.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/vivid-cool.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/vivid-lut.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/vivid-lut.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/vivid-warm.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/vivid-warm.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_lut/yuanqi-2.2s.cube.rgb.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_lut/yuanqi-2.2s.cube.rgb.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_res/.DS_Store:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_res/.DS_Store \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_res/film_grain_small.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_res/film_grain_small.bin \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_res/lut_all_points.png:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_res/lut_all_points.png \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_res/overlay_p4_3_weak.png:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_res/overlay_p4_3_weak.png \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_res/pacman.json:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_res/pacman.json \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_res/textures/.DS_Store:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_res/textures/.DS_Store \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_res/textures/pac00001.png:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_res/textures/pac00001.png \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_res/textures/pac00002.png:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_res/textures/pac00002.png \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_res/textures/pac00003.png:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_res/textures/pac00003.png \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_res/textures/pac00004.png:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_res/textures/pac00004.png \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_res/textures/pac00005.png:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_res/textures/pac00005.png \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_res/textures/pacman_01.png:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_res/textures/pacman_01.png \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_res/textures/pacman_02.png:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_res/textures/pacman_02.png \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_res/textures/pacman_07.png:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_res/textures/pacman_07.png \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/filters_res/textures/pacman_08.png:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/filters_res/textures/pacman_08.png \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/samplenode/tuning/sample_tuning_1.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/samplenode/tuning/sample_tuning_1.txt \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/3rdpool/samplenode/tuning/sample_tuning_2.txt:$(TARGET_COPY_OUT_ODM)/etc/camera/3rdpool/samplenode/tuning/sample_tuning_2.txt \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/CameraHWConfiguration.config:$(TARGET_COPY_OUT_ODM)/etc/camera/CameraHWConfiguration.config \
    vendor/realme/RE58C2/proprietary/odm/etc/camera/fwk_config.json:$(TARGET_COPY_OUT_ODM)/etc/camera/fwk_config.json \
    vendor/realme/RE58C2/proprietary/odm/etc/init/init.jiiov.rc:$(TARGET_COPY_OUT_ODM)/etc/init/init.jiiov.rc \
    vendor/realme/RE58C2/proprietary/odm/etc/isppipeline/Pipeline_Linkage.json:$(TARGET_COPY_OUT_ODM)/etc/isppipeline/Pipeline_Linkage.json \
    vendor/realme/RE58C2/proprietary/odm/etc/isppipeline/props.xml:$(TARGET_COPY_OUT_ODM)/etc/isppipeline/props.xml \
    vendor/realme/RE58C2/proprietary/odm/etc/libnfc_accesscard_config.conf:$(TARGET_COPY_OUT_ODM)/etc/libnfc_accesscard_config.conf \
    vendor/realme/RE58C2/proprietary/odm/etc/libnfc_default_config.conf:$(TARGET_COPY_OUT_ODM)/etc/libnfc_default_config.conf \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/common/DefaultNodeList.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/common/DefaultNodeList.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/pipeline/Pipeline_App_Yuv_Capture.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/pipeline/Pipeline_App_Yuv_Capture.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/pipeline/Pipeline_Async.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/pipeline/Pipeline_Async.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/pipeline/Pipeline_FaceID_Callback.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/pipeline/Pipeline_FaceID_Callback.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/pipeline/Pipeline_FaceID_Preview.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/pipeline/Pipeline_FaceID_Preview.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/pipeline/Pipeline_Front_Auto_Callback.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/pipeline/Pipeline_Front_Auto_Callback.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/pipeline/Pipeline_Front_Auto_Capture.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/pipeline/Pipeline_Front_Auto_Capture.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/pipeline/Pipeline_Front_Auto_Preview.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/pipeline/Pipeline_Front_Auto_Preview.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/pipeline/Pipeline_Front_Auto_Video.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/pipeline/Pipeline_Front_Auto_Video.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/pipeline/Pipeline_Front_HighRes_Capture.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/pipeline/Pipeline_Front_HighRes_Capture.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/pipeline/Pipeline_Front_HighRes_Preview.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/pipeline/Pipeline_Front_HighRes_Preview.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/pipeline/Pipeline_Front_NightPro_Capture.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/pipeline/Pipeline_Front_NightPro_Capture.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/pipeline/Pipeline_Front_NightPro_Preview.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/pipeline/Pipeline_Front_NightPro_Preview.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/pipeline/Pipeline_Multimode_Callback.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/pipeline/Pipeline_Multimode_Callback.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/pipeline/Pipeline_Multimode_Preview.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/pipeline/Pipeline_Multimode_Preview.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/pipeline/Pipeline_Rear_Auto_Callback.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/pipeline/Pipeline_Rear_Auto_Callback.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/pipeline/Pipeline_Rear_Auto_Capture.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/pipeline/Pipeline_Rear_Auto_Capture.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/pipeline/Pipeline_Rear_Auto_Debug_Reprocess.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/pipeline/Pipeline_Rear_Auto_Debug_Reprocess.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/pipeline/Pipeline_Rear_Auto_Preview.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/pipeline/Pipeline_Rear_Auto_Preview.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/pipeline/Pipeline_Rear_Auto_Video.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/pipeline/Pipeline_Rear_Auto_Video.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/pipeline/Pipeline_Rear_DualCam_Capture.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/pipeline/Pipeline_Rear_DualCam_Capture.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/pipeline/Pipeline_Rear_DualCam_Preview.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/pipeline/Pipeline_Rear_DualCam_Preview.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/pipeline/Pipeline_Rear_HighRes_Capture.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/pipeline/Pipeline_Rear_HighRes_Capture.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/pipeline/Pipeline_Rear_HighRes_Preview.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/pipeline/Pipeline_Rear_HighRes_Preview.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/pipeline/Pipeline_Rear_NightPro_Capture.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/pipeline/Pipeline_Rear_NightPro_Capture.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/pipeline/Pipeline_Rear_NightPro_Preview.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/pipeline/Pipeline_Rear_NightPro_Preview.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/pipeline/Pipeline_Rear_Professional_Capture.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/pipeline/Pipeline_Rear_Professional_Capture.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/pipeline/Pipeline_Single_Portrait_Capture.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/pipeline/Pipeline_Single_Portrait_Capture.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/pipeline/Pipeline_Single_Portrait_Preview.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/pipeline/Pipeline_Single_Portrait_Preview.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/pipeline/Pipeline_Slowmotion.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/pipeline/Pipeline_Slowmotion.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/pipeline/Pipeline_ThirdParty_Async.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/pipeline/Pipeline_ThirdParty_Async.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/pipeline/Pipeline_ThirdParty_Auto_Callback.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/pipeline/Pipeline_ThirdParty_Auto_Callback.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/pipeline/Pipeline_ThirdParty_Auto_Capture.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/pipeline/Pipeline_ThirdParty_Auto_Capture.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/pipeline/Pipeline_ThirdParty_Auto_Preview.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/pipeline/Pipeline_ThirdParty_Auto_Preview.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/pipeline/Pipeline_ThirdParty_Auto_Video.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/pipeline/Pipeline_ThirdParty_Auto_Video.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/pipeline/Pipeline_Ultrawide_Capture.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/pipeline/Pipeline_Ultrawide_Capture.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/pipeline/Pipeline_Ultrawide_Preview.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/pipeline/Pipeline_Ultrawide_Preview.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/pipeline/Pipeline_Ultrawide_Video.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/pipeline/Pipeline_Ultrawide_Video.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/pipeline/Pipeline_Ultrawide_Video_Preview.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/pipeline/Pipeline_Ultrawide_Video_Preview.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/pipeline/Pipeline_Video_Capture.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/pipeline/Pipeline_Video_Capture.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/plugin/LwpPlugin.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/plugin/LwpPlugin.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/session/Session_Front_AutoDC.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/session/Session_Front_AutoDC.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/session/Session_Front_Auto_Video.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/session/Session_Front_Auto_Video.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/session/Session_Front_HighResolution.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/session/Session_Front_HighResolution.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/session/Session_Front_LargeAperture.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/session/Session_Front_LargeAperture.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/session/Session_Front_NightPro.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/session/Session_Front_NightPro.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/session/Session_Front_Portrait.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/session/Session_Front_Portrait.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/session/Session_Front_Single_FaceID.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/session/Session_Front_Single_FaceID.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/session/Session_Rear_AutoDC.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/session/Session_Rear_AutoDC.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/session/Session_Rear_Auto_Video.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/session/Session_Rear_Auto_Video.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/session/Session_Rear_DualCamera.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/session/Session_Rear_DualCamera.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/session/Session_Rear_HighResolution.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/session/Session_Rear_HighResolution.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/session/Session_Rear_LargeAperture.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/session/Session_Rear_LargeAperture.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/session/Session_Rear_NightPro.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/session/Session_Rear_NightPro.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/session/Session_Rear_NightVideo.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/session/Session_Rear_NightVideo.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/session/Session_Rear_Panorama.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/session/Session_Rear_Panorama.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/session/Session_Rear_Portrait.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/session/Session_Rear_Portrait.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/session/Session_Rear_Professional.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/session/Session_Rear_Professional.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/session/Session_Rear_Qrcode.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/session/Session_Rear_Qrcode.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/session/Session_Rear_Slowmotion.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/session/Session_Rear_Slowmotion.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/session/Session_Rear_Timelapse.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/session/Session_Rear_Timelapse.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/session/Session_Single_Portrait.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/session/Session_Single_Portrait.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/session/Session_ThirdParty.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/session/Session_ThirdParty.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/session/Session_Ultrawide.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/session/Session_Ultrawide.json \
    vendor/realme/RE58C2/proprietary/odm/etc/lwp/Topology/session/Session_Ultrawide_Video.json:$(TARGET_COPY_OUT_ODM)/etc/lwp/Topology/session/Session_Ultrawide_Video.json \
    vendor/realme/RE58C2/proprietary/odm/etc/media_codecs_c2_secure.xml:$(TARGET_COPY_OUT_ODM)/etc/media_codecs_c2_secure.xml \
    vendor/realme/RE58C2/proprietary/odm/etc/media_codecs_performance_c2_secure.xml:$(TARGET_COPY_OUT_ODM)/etc/media_codecs_performance_c2_secure.xml \
    vendor/realme/RE58C2/proprietary/odm/etc/otpdata/input_parameters_values.txt:$(TARGET_COPY_OUT_ODM)/etc/otpdata/input_parameters_values.txt \
    vendor/realme/RE58C2/proprietary/odm/etc/otpdata/obj_disc.txt:$(TARGET_COPY_OUT_ODM)/etc/otpdata/obj_disc.txt \
    vendor/realme/RE58C2/proprietary/odm/etc/otpdata/otpgoldendata.txt:$(TARGET_COPY_OUT_ODM)/etc/otpdata/otpgoldendata.txt \
    vendor/realme/RE58C2/proprietary/odm/etc/otpdata/oz1_input_parameters_values.txt:$(TARGET_COPY_OUT_ODM)/etc/otpdata/oz1_input_parameters_values.txt \
    vendor/realme/RE58C2/proprietary/odm/etc/otpdata/oz2_input_parameters_values.txt:$(TARGET_COPY_OUT_ODM)/etc/otpdata/oz2_input_parameters_values.txt \
    vendor/realme/RE58C2/proprietary/odm/etc/otpdata/sale_after_input_parameters_values.txt:$(TARGET_COPY_OUT_ODM)/etc/otpdata/sale_after_input_parameters_values.txt \
    vendor/realme/RE58C2/proprietary/odm/etc/otpdata/sell_aft_cali.txt:$(TARGET_COPY_OUT_ODM)/etc/otpdata/sell_aft_cali.txt \
    vendor/realme/RE58C2/proprietary/odm/etc/otpdata/spw_input_parameters_values.txt:$(TARGET_COPY_OUT_ODM)/etc/otpdata/spw_input_parameters_values.txt \
    vendor/realme/RE58C2/proprietary/odm/etc/otpdata/spw_input_parameters_values_planar.txt:$(TARGET_COPY_OUT_ODM)/etc/otpdata/spw_input_parameters_values_planar.txt \
    vendor/realme/RE58C2/proprietary/odm/etc/sensor_config.xml:$(TARGET_COPY_OUT_ODM)/etc/sensor_config.xml \
    vendor/realme/RE58C2/proprietary/odm/etc/unipnp/UniFeature.xml:$(TARGET_COPY_OUT_ODM)/etc/unipnp/UniFeature.xml \
    vendor/realme/RE58C2/proprietary/odm/etc/wifi_board_config.ini:$(TARGET_COPY_OUT_ODM)/etc/wifi_board_config.ini \
    vendor/realme/RE58C2/proprietary/odm/etc/wifi_board_config_aa.ini:$(TARGET_COPY_OUT_ODM)/etc/wifi_board_config_aa.ini \
    vendor/realme/RE58C2/proprietary/odm/etc/wifi_board_config_hulk.ini:$(TARGET_COPY_OUT_ODM)/etc/wifi_board_config_hulk.ini \
    vendor/realme/RE58C2/proprietary/odm/etc/wifi_board_config_hulkbc.ini:$(TARGET_COPY_OUT_ODM)/etc/wifi_board_config_hulkbc.ini \
    vendor/realme/RE58C2/proprietary/odm/etc/zoom_config.json:$(TARGET_COPY_OUT_ODM)/etc/zoom_config.json \
    vendor/realme/RE58C2/proprietary/odm/lib/libBokeh2Frames.so:$(TARGET_COPY_OUT_ODM)/lib/libBokeh2Frames.so \
    vendor/realme/RE58C2/proprietary/odm/lib/libDefog.so:$(TARGET_COPY_OUT_ODM)/lib/libDefog.so \
    vendor/realme/RE58C2/proprietary/odm/lib/libSegLite.so:$(TARGET_COPY_OUT_ODM)/lib/libSegLite.so \
    vendor/realme/RE58C2/proprietary/odm/lib/libTfliteWrapper.so:$(TARGET_COPY_OUT_ODM)/lib/libTfliteWrapper.so \
    vendor/realme/RE58C2/proprietary/odm/lib/libbokeh_gaussian_cap.so:$(TARGET_COPY_OUT_ODM)/lib/libbokeh_gaussian_cap.so \
    vendor/realme/RE58C2/proprietary/odm/lib/libinfo.so:$(TARGET_COPY_OUT_ODM)/lib/libinfo.so \
    vendor/realme/RE58C2/proprietary/odm/lib/libinterface.so:$(TARGET_COPY_OUT_ODM)/lib/libinterface.so \
    vendor/realme/RE58C2/proprietary/odm/lib/libkey.so:$(TARGET_COPY_OUT_ODM)/lib/libkey.so \
    vendor/realme/RE58C2/proprietary/odm/lib/libsprdbokeh.so:$(TARGET_COPY_OUT_ODM)/lib/libsprdbokeh.so \
    vendor/realme/RE58C2/proprietary/odm/lib/libverify.so:$(TARGET_COPY_OUT_ODM)/lib/libverify.so \
    vendor/realme/RE58C2/proprietary/odm/lib64/libBokeh2Frames.so:$(TARGET_COPY_OUT_ODM)/lib64/libBokeh2Frames.so \
    vendor/realme/RE58C2/proprietary/odm/lib64/libDefog.so:$(TARGET_COPY_OUT_ODM)/lib64/libDefog.so \
    vendor/realme/RE58C2/proprietary/odm/lib64/libSegLite.so:$(TARGET_COPY_OUT_ODM)/lib64/libSegLite.so \
    vendor/realme/RE58C2/proprietary/odm/lib64/libTfliteWrapper.so:$(TARGET_COPY_OUT_ODM)/lib64/libTfliteWrapper.so \
    vendor/realme/RE58C2/proprietary/odm/lib64/libbokeh_gaussian_cap.so:$(TARGET_COPY_OUT_ODM)/lib64/libbokeh_gaussian_cap.so \
    vendor/realme/RE58C2/proprietary/odm/lib64/libinfo.so:$(TARGET_COPY_OUT_ODM)/lib64/libinfo.so \
    vendor/realme/RE58C2/proprietary/odm/lib64/libinterface.so:$(TARGET_COPY_OUT_ODM)/lib64/libinterface.so \
    vendor/realme/RE58C2/proprietary/odm/lib64/libkey.so:$(TARGET_COPY_OUT_ODM)/lib64/libkey.so \
    vendor/realme/RE58C2/proprietary/odm/lib64/libsprdbokeh.so:$(TARGET_COPY_OUT_ODM)/lib64/libsprdbokeh.so \
    vendor/realme/RE58C2/proprietary/odm/lib64/libverify.so:$(TARGET_COPY_OUT_ODM)/lib64/libverify.so \
    vendor/realme/RE58C2/proprietary/system_ext/etc/camera/default_cnr3_param.txt:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/camera/default_cnr3_param.txt \
    vendor/realme/RE58C2/proprietary/system_ext/etc/camera/default_ynr_param.txt:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/camera/default_ynr_param.txt \
    vendor/realme/RE58C2/proprietary/system_ext/etc/init/dataLogDaemon.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/dataLogDaemon.rc \
    vendor/realme/RE58C2/proprietary/system_ext/etc/init/data_rps.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/data_rps.rc \

# ==================================================
# Realme RE58C2 Vendor Blobs - Complete File List
# ==================================================

PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/android.hardware.audio.service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.audio.service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/android.hardware.biometrics.fingerprint@2.1-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.biometrics.fingerprint@2.1-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/android.hardware.bluetooth@1.1-service.unisoc:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.bluetooth@1.1-service.unisoc \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/android.hardware.camera.provider@2.4-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.camera.provider@2.4-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/android.hardware.cas@1.2-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.cas@1.2-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/android.hardware.drm-service.clearkey:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.drm-service.clearkey \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/android.hardware.drm-service.widevine:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.drm-service.widevine \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/android.hardware.gatekeeper@1.0-service.trusty:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.gatekeeper@1.0-service.trusty \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/android.hardware.graphics.allocator@4.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.graphics.allocator@4.0-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/android.hardware.graphics.composer@2.4-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.graphics.composer@2.4-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/android.hardware.health-service.example:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.health-service.example \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/android.hardware.media.c2@1.1-unisoc-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.media.c2@1.1-unisoc-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/android.hardware.media.omx@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.media.omx@1.0-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/android.hardware.neuralnetworks@1.3-service-armnn-gpu:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.neuralnetworks@1.3-service-armnn-gpu \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/android.hardware.nfc@1.2-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.nfc@1.2-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/android.hardware.power.stats-service.example:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.power.stats-service.example \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/android.hardware.rebootescrow-service.default:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.rebootescrow-service.default \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/android.hardware.security.keymint@2.0-unisoc.service.trusty:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.security.keymint@2.0-unisoc.service.trusty \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/android.hardware.sensors-service.multihal:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.sensors-service.multihal \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/android.hardware.usb-service.example:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.usb-service.example \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/android.hardware.wifi@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.wifi@1.0-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/hostapd:$(TARGET_COPY_OUT_VENDOR)/bin/hw/hostapd \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/urild:$(TARGET_COPY_OUT_VENDOR)/bin/hw/urild \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.oppo.engnative.engineer@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.oppo.engnative.engineer@1.0-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.biometrics.face-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.biometrics.face-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.boot@1.2-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.boot@1.2-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.broadcastradio@2.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.broadcastradio@2.0-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.commondcs@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.commondcs@1.0-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.connmgr@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.connmgr@1.0-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.cplog_svc-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.cplog_svc-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.enhance-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.enhance-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.fingerprintmmi-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.fingerprintmmi-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.gnss@2.2-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.gnss@2.2-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.hdcp-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.hdcp-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.lights-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.lights-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.log-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.log-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.memtrack-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.memtrack-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.network@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.network@1.0-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.network-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.network-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.oemlock-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.oemlock-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.performance@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.performance@1.0-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.soter-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.soter-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.thermal@2.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.thermal@2.0-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.trusty-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.trusty-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.tui-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.tui-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.vibrator-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.vibrator-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.sprd.hardware.wcn@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.sprd.hardware.wcn@1.0-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.unisoc.hardware.ai_engine-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.unisoc.hardware.ai_engine-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/vendor.unisoc.hardware.power-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.unisoc.hardware.power-service \
    vendor/realme/RE58C2/proprietary/vendor/bin/hw/wpa_supplicant:$(TARGET_COPY_OUT_VENDOR)/bin/hw/wpa_supplicant

# etc/audio_config.xml
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/etc/audio_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_config.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/audio_effects.conf:$(TARGET_COPY_OUT_VENDOR)/etc/audio_effects.conf \
    vendor/realme/RE58C2/proprietary/vendor/etc/audio_effects.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_effects.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_configuration.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/audio_policy_volumes.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_volumes.xml

# etc/init/
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.audio.service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.audio.service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.biometrics.fingerprint@2.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.biometrics.fingerprint@2.1-service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.bluetooth@1.1-service.unisoc.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.1-service.unisoc.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.camera.provider@2.4-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.camera.provider@2.4-service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.drm-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm-service.widevine.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.graphics.composer@2.4-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.graphics.composer@2.4-service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.media.omx@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.media.omx@1.0-service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.nfc@1.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.nfc@1.2-service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/android.hardware.wifi@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.wifi@1.0-service.rc \
    vendor/realme/RE58C2/proprietary/vendor/etc/init/vendor.sprd.hardware.thermal@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sprd.hardware.thermal@2.0-service.rc

# lib/
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/lib/android.hardware.camera.provider@2.4-external-sprd.so:$(TARGET_COPY_OUT_VENDOR)/lib/android.hardware.camera.provider@2.4-external-sprd.so \
    vendor/realme/RE58C2/proprietary/vendor/lib/android.hardware.camera.provider@2.4-legacy-sprd.so:$(TARGET_COPY_OUT_VENDOR)/lib/android.hardware.camera.provider@2.4-legacy-sprd.so \
    vendor/realme/RE58C2/proprietary/vendor/lib/camera.device@3.4-impl-sprd.so:$(TARGET_COPY_OUT_VENDOR)/lib/camera.device@3.4-impl-sprd.so \
    vendor/realme/RE58C2/proprietary/vendor/lib/libGLES_mali.so:$(TARGET_COPY_OUT_VENDOR)/lib/libGLES_mali.so \
    vendor/realme/RE58C2/proprietary/vendor/lib/egl/libGLES_mali.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLES_mali.so \
    vendor/realme/RE58C2/proprietary/vendor/lib/hw/gralloc.default.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gralloc.default.so \
    vendor/realme/RE58C2/proprietary/vendor/lib/hw/hwcomposer.unisoc.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/hwcomposer.unisoc.so

# lib64/
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/lib64/android.hardware.camera.provider@2.4-external-sprd.so:$(TARGET_COPY_OUT_VENDOR)/lib64/android.hardware.camera.provider@2.4-external-sprd.so \
    vendor/realme/RE58C2/proprietary/vendor/lib64/android.hardware.camera.provider@2.4-impl-sprd.so:$(TARGET_COPY_OUT_VENDOR)/lib64/android.hardware.camera.provider@2.4-impl-sprd.so \
    vendor/realme/RE58C2/proprietary/vendor/lib64/libGLES_mali.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libGLES_mali.so \
    vendor/realme/RE58C2/proprietary/vendor/lib64/egl/libGLES_mali.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libGLES_mali.so \
    vendor/realme/RE58C2/proprietary/vendor/lib64/hw/gralloc.default.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/gralloc.default.so \
    vendor/realme/RE58C2/proprietary/vendor/lib64/hw/hwcomposer.unisoc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/hwcomposer.unisoc.so

# etc/permissions/
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor/etc/permissions/android.hardware.fingerprint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.fingerprint.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/permissions/android.hardware.telephony.gsm.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.telephony.gsm.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/permissions/android.hardware.wifi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.wifi.xml \
    vendor/realme/RE58C2/proprietary/vendor/etc/permissions/handheld_core_hardware.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/handheld_core_hardware.xml



# =============================================
# Vendor DLKM Modules
# =============================================

# Kernel modules (bulk copy)
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*.ko,vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules,$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules)

#PRODUCT_COPY_FILES += \
#     vendor/realme/RE58C2/proprietary/vendor_dlkm/etc/init/init.realme.rc:$(TARGET_COPY_OUT_VENDOR_DLKM)/etc/init/init.realme.rc

# Module metadata files
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules/modules.alias:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/modules.alias \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules/modules.dep:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/modules.dep \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules/modules.softdep:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/modules.softdep

# Module loading configs
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules/modules.load:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/modules.load \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules/modules.load.cali:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/modules.load.cali \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules/modules.load.charger:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/modules.load.charger

# Critical hardware modules (explicit copies)
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules/mali_kbase.ko:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/mali_kbase.ko \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules/sprd_wlan_combo.ko:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/sprd_wlan_combo.ko \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules/sprd_thermal.ko:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/sprd_thermal.ko

# Init configuration
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/lib/modules/init.insmod.cfg:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/init.insmod.cfg

# Build properties
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/etc/build.prop:s$(TARGET_COPY_OUT_VENDOR_DLKM)/etc/build.prop

# Filesystem config
PRODUCT_COPY_FILES += \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/etc/fs_config_dirs:$(TARGET_COPY_OUT_VENDOR_DLKM)/etc/fs_config_dirs \
    vendor/realme/RE58C2/proprietary/vendor_dlkm/etc/fs_config_files:$(TARGET_COPY_OUT_VENDOR_DLKM)/etc/fs_config_files

# =============================================
# Critical Vendor DLKM Binaries
# =============================================
#PRODUCT_COPY_FILES += \
#    vendor/realme/RE58C2/proprietary/vendor_dlkm/bin/modprobe:$(TARGET_COPY_OUT_VENDOR_DLKM)/bin/modprobe


#load the loadable
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,vendor/realme/RE58C2/proprietary/vendor/bin,$(TARGET_COPY_OUT_VENDOR)/bin) \
    $(call find-copy-subdir-files,*,vendor/realme/RE58C2/proprietary/vendor/lib,$(TARGET_COPY_OUT_VENDOR)/lib) \
    $(call find-copy-subdir-files,*,vendor/realme/RE58C2/proprietary/vendor/lib64,$(TARGET_COPY_OUT_VENDOR)/lib64) \
    $(call find-copy-subdir-files,*,vendor/realme/RE58C2/proprietary/vendor/etc/init,$(TARGET_COPY_OUT_VENDOR)/etc/init) \





# ========================
# Core Android HAL Services
# ========================
PRODUCT_PACKAGES += \
    android.hardware.health@2.0-service \
    android.hardware.wifi@1.0-service \
    android.hardware.renderscript@1.0-impl \
    android.hardware.camera.provider@2.4-impl-sprd \
    android.hardware.camera.provider@2.4-external-sprd \
    android.hardware.camera.provider@2.4-legacy-sprd \
    android.hardware.sensors@2.X-sprd_subhal

# ========================
# Vendor HAL Implementations
# ========================

# Hardware HAL Services
PRODUCT_PACKAGES += \
    android.hardware.gatekeeper@1.0-service.trusty \
    android.hardware.power-service.example \
    android.hardware.health-service.example \
    android.hardware.bluetooth@1.1-service.unisoc \
    android.hardware.usb-service.example \
    android.hardware.graphics.allocator@4.0-service \
    android.hardware.graphics.composer@2.4-service \
    android.hardware.audio.service \
    android.hardware.drm-service.clearkey \
    android.hardware.drm-service.widevine \
    android.hardware.rebootescrow-service.default \
    android.hardware.power.stats-service.example

# Vendor-specific Services
PRODUCT_PACKAGES += \
    vendor.sprd.hardware.soter-service \
    vendor.sprd.hardware.thermal@2.0-service \
    vendor.sprd.hardware.oemlock-service \
    vendor.sprd.hardware.enhance-service \
    vendor.sprd.hardware.log-service \
    vendor.sprd.hardware.hdcp-service

# Charger
PRODUCT_PACKAGES += \
    charger \
    charger_res_images


# ========================
# SPRD-specific Components
# ========================
# Connectivity Management
PRODUCT_PACKAGES += \
    vendor.sprd.hardware.connmgr@1.0-service \
    vendor.sprd.hardware.connmgr@1.0-impl

# Boot & Trusty Services
PRODUCT_PACKAGES += \
    vendor.sprd.hardware.boot@1.2-service \
    vendor.sprd.hardware.trusty-service \
    vendor.sprd.hardware.trusty-impl

# TUI (Trusted UI) Components
PRODUCT_PACKAGES += \
    vendor.sprd.hardware.tui-service \
    vendor.sprd.hardware.tui@1.0-impl

# Hardware Control Services
PRODUCT_PACKAGES += \
    vendor.sprd.hardware.vibrator-service \
    vendor.sprd.hardware.lights-service \
    vendor.sprd.hardware.memtrack-service

# Performance Management
PRODUCT_PACKAGES += \
    vendor.sprd.hardware.performance@1.0-service \
    vendor.sprd.hardware.performance@1.0-impl

# Wireless Components
PRODUCT_PACKAGES += \
    vendor.sprd.hardware.wcn@1.0-service \
    vendor.sprd.hardware.wcn@1.0-impl \
    vendor.sprd.hardware.network@1.0-service \
    vendor.sprd.hardware.network@1.0-impl

# GNSS/GPS Components
PRODUCT_PACKAGES += \
    vendor.sprd.hardware.gnss@1.0-service \
    vendor.sprd.hardware.gnss@1.0-impl \
    gpsd_sprd \
    gps.default

# Thermal Management
PRODUCT_PACKAGES += \
    vendor.sprd.hardware.thermal@1.0 \
    vendor.sprd.hardware.thermal@2.0-service \
    vendor.sprd.hardware.thermal@2.0-impl

# Diagnostic & Logging Services
PRODUCT_PACKAGES += \
    vendor.sprd.hardware.commondcs@1.0-service \
    vendor.sprd.hardware.commondcs@1.0-impl \
    vendor.sprd.hardware.cplog_svc@1.0-service

# Broadcast & Algorithm Services
PRODUCT_PACKAGES += \
    vendor.sprd.hardware.broadcastradio@2.0-service \
    vendor.sprd.algoservice@1.0

# ========================
# Security Services
# ========================
PRODUCT_PACKAGES += \
    android.hardware.security.keymint@2.0-unisoc.service.trusty \
    vendor.tee_rpc \
    vendor.rpmbserver \
    vndservicemanager \
    vendor.rpmbproxy \
    vendor.nsproxy \
    vendor.teensproxy \
    vendor.tsupplicant \
    vendor.tsupplicant-cali

# ========================
# Connectivity Services
# ========================
PRODUCT_PACKAGES += \
    wpa_supplicant \
    hostapd \
    android.hardware.wifi@1.0-service \
    vendor.wcn@1.0-service \
    vendor.wcn_chr

# ========================
# Camera/Media Services
# ========================
PRODUCT_PACKAGES += \
    android.hardware.camera.provider@2.4-service \
    android.hardware.media.omx@1.0-service \
    media.codec2.unisoc.service \
    remosaic_daemon

# ========================
# Modem/Sensors
# ========================
PRODUCT_PACKAGES += \
    android.hardware.sensors-service.multihal \
    slogmodem \
    modem_control \
    rild \
    vendor.stk

# ========================
# Realme/Oppo Specific
# ========================
PRODUCT_PACKAGES += \
    wifisar_realme \
    vendor.oppo.engnative.engineer@1.0-service \
    vendor.sprd.hardware.biometrics.face-service \
    vendor.sprd.hardware.fingerprintmmi-service

# ========================
# Debug/Utility Services
# ========================
PRODUCT_PACKAGES += \
    phasecheckserver \
    engpc \
    cplog_svc \
    yloglite \
    srtd \
    dcxsrv \
    systemDebuggerd

# ========================
# Thermal/Power Management
# ========================
PRODUCT_PACKAGES += \
    thermald \
    vendor.charged \
    refnotify

# ========================
# AI/Neural Networks
# ========================
PRODUCT_PACKAGES += \
    vendor.unisoc.hardware.ai_engine-service \
    android.hardware.neuralnetworks@1.3-service-armnn-gpu

# ========================
# Storage Services
# ========================
PRODUCT_PACKAGES += \
    cp_diskserver \
    android.hardware.cas@1.2-service

# ========================
# Network Services
# ========================
PRODUCT_PACKAGES += \
    vendor.sprd.hardware.network@1.0-service

# ========================
# NXP NFC Components
# ========================
PRODUCT_PACKAGES += \
    vendor.nxp.eventprocessor@1.0-service \
    vendor.nxp.nxpnfclegacy@1.0-service

# ========================
# Boot/Init Services
# ========================
PRODUCT_PACKAGES += \
    uniber \
    watchdogd

# Kernel Modules (Critical ones only)
PRODUCT_PACKAGES += \
    mali_kbase.ko \
    sprd_wlan_combo.ko \
    sprd_thermal.ko \
    sprd_camera.ko \
    sprdbt_tty.ko

# Module Management Utilities
PRODUCT_PACKAGES += \
    modprobe_vendor_dlkm \
    depmod_vendor_dlkm

# Init Services
PRODUCT_PACKAGES += \
    vendor_dlkm_modules_loading \
    vendor_dlkm_early_init


